/*
 * This file is part of GuardAC - https://github.com/PalassCQ/GuardAC
 * Copyright (C) 2026 GuardAC
 *
 * GuardAC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GuardAC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * This file contains code derived from:
 *   - Shard (© 2026 KaelusAI, https://github.com/KaelusAI/Shard)
 *   - Grim (© 2025 GrimAnticheat, https://github.com/GrimAnticheat/Grim)
 * All derived code is licensed under GPL-3.0.
 */

package dev.guardac.util

enum class Message(val key: String) {
    PREFIX("prefix"),
    NO_PERMISSION("no-permission"),
    PLAYER_NOT_FOUND("player-not-found"),
    RUN_AS_PLAYER("run-as-player"),
    RELOAD_SUCCESS("reload-success"),

    ALERTS_ENABLED("alerts-enabled"),
    ALERTS_DISABLED("alerts-disabled"),
    ALERTS_FORMAT("alerts-format"),
    ALERTS_DIGEST_FORMAT("alerts-digest-format"),
    ALERTS_CONSOLE_FORMAT("alerts-console-format"),
    FINGERPRINT_ALERT("fingerprint-alert"),
    SUSPICIOUS_ALERT("suspicious-alert"),
    UPDATE_DOWNLOADED("update-downloaded"),

    SUPPRESSION_ISOLATE_NOTICE("suppression-isolate-notice"),
    PROFILE_SUPPRESSION("profile-suppression"),
    DEBUG_SUPPRESSION("debug-suppression"),

    PROFILE_HEADER("profile-header"),
    PROFILE_AI_BUFFER("profile-ai-buffer"),
    PROFILE_AI_VL("profile-ai-vl"),
    PROFILE_NO_DATA("profile-no-data"),
    PROFILE_PING("profile-ping"),
    PROFILE_SESSION("profile-session"),
    PROFILE_SENSITIVITY("profile-sensitivity"),
    PROFILE_RIDING("profile-riding"),
    PROFILE_BRAND("profile-brand"),
    PROFILE_AVG_PROB("profile-avg-prob"),
    PROFILE_NOT_CHECKED("profile-not-checked"),
    SKIP_AI_OFF("skip-ai-off"),
    SKIP_BYPASS("skip-bypass"),
    SKIP_EXEMPT("skip-exempt"),
    SKIP_EXEMPT_GLOBAL("skip-exempt-global"),
    SKIP_BEDROCK("skip-bedrock"),
    SKIP_REGION("skip-region"),
    SKIP_RIDING("skip-riding"),
    PROFILE_JUDGE("profile-judge"),
    PROFILE_JUDGE_LOCAL("profile-judge-local"),

    DEBUG_HEADER("debug-header"),
    DEBUG_ROTATION("debug-rotation"),
    DEBUG_DELTA("debug-delta"),
    DEBUG_ACCEL("debug-accel"),
    DEBUG_JERK("debug-jerk"),
    DEBUG_GCD("debug-gcd"),
    DEBUG_MODE_XY("debug-mode-xy"),
    DEBUG_AI_BUFFER("debug-ai-buffer"),
    DEBUG_RIDING("debug-riding"),
    DEBUG_MODE_STATUS("debug-mode-status"),
    DEBUG_MODE_ON("debug-mode-on"),
    DEBUG_MODE_OFF("debug-mode-off"),
    DEBUG_IDLE("debug-idle"),

    PROB_STARTED("prob-started"),
    PROB_STOPPED("prob-stopped"),
    PROB_ACTIONBAR("prob-display"),
    PROB_NO_DATA("prob-no-data"),

    WEB_BAN_EXECUTED("web-ban-executed"),
    WEB_BAN_KICK("web-ban-kick"),
    WEB_UNBAN_EXECUTED("web-unban-executed"),

    MONITOR_ENABLED("monitor-enabled"),
    MONITOR_DISABLED("monitor-disabled"),
    MONITOR_HIT("monitor-hit"),

    EXEMPT_ADDED("exempt-added"),
    EXEMPT_REMOVED("exempt-removed"),
    EXEMPT_STATUS_EXEMPT("exempt-status-exempt"),
    EXEMPT_STATUS_NOT_EXEMPT("exempt-status-not-exempt"),
    EXEMPT_ALREADY("exempt-already"),
    EXEMPT_NOT_FOUND("exempt-not-found"),

    OVERHEAD_SHOWN("overhead-shown"),
    OVERHEAD_HIDDEN("overhead-hidden"),
    USAGE_AVG("usage-avg"),
    HELP_AVG("help-overhead"),

    PUNISH_SUCCESS("punish-success"),
    PUNISH_SUCCESS_ANIMATED("punish-success-animated"),
    PUNISH_UNKNOWN_ANIMATION("punish-unknown-animation"),
    PUNISH_DISABLED_ANIMATION("punish-disabled-animation"),
    PUNISH_NO_DATA("punish-no-data"),
    UNSAFE_NAME_KICK("unsafe-name-kick"),

    RESET_SUCCESS("reset-success"),
    USAGE_RESET("usage-reset"),
    HELP_RESET("help-reset"),

    HEALTH_HEADER("health-header"),
    HEALTH_BUILD("health-build"),
    HEALTH_BACKEND("health-backend"),
    HEALTH_MODE("health-mode"),
    HEALTH_KEY("health-key"),
    HEALTH_JUDGE("health-judge"),
    HEALTH_JUDGE_ACTIVE("health-judge-active"),
    HEALTH_JUDGE_NONE("health-judge-none"),
    HEALTH_JUDGE_UNKNOWN("health-judge-unknown"),
    HEALTH_TPS("health-tps"),
    HEALTH_TRACKED("health-tracked"),
    HEALTH_MODULES("health-modules"),
    HEALTH_OK("health-ok"),
    HEALTH_DEGRADED("health-degraded"),
    HEALTH_OFF("health-off"),
    HEALTH_MISSING("health-missing"),
    HEALTH_ENFORCING("health-enforcing"),
    HEALTH_ALERT_ONLY("health-alert-only"),
    HELP_HEALTH("help-health"),

    VERSION_HEADER("version-header"),
    VERSION_BUILD("version-build"),
    VERSION_SERVER("version-server"),
    VERSION_JAVA("version-java"),
    HELP_VERSION("help-version"),

    STATS_HEADER("stats-header"),
    STATS_ONLINE("stats-online"),
    STATS_SUSPICIOUS("stats-suspicious"),
    STATS_TOTAL_FLAGS("stats-total-flags"),
    STATS_AI_STATUS("stats-ai-status"),
    STATS_DC_SESSIONS("stats-dc-sessions"),
    STATS_UPTIME("stats-uptime"),

    TOP_HEADER("top-header"),
    TOP_ENTRY("top-entry"),
    TOP_EMPTY("top-empty"),
    USAGE_TOP("usage-top"),
    HELP_TOP("help-top"),

    LOG_HEADER("log-header"),
    LOG_EMPTY("log-empty"),

    HISTORY_HEADER("history-header"),
    HISTORY_ENTRY("history-entry"),
    HISTORY_EMPTY("history-empty"),
    USAGE_HISTORY("usage-history"),
    HELP_HISTORY("help-history"),

    RESULTS_MENU_TITLE("results-menu-title"),
    RESULTS_EMPTY("results-empty"),
    RESULTS_HEAD_TITLE("results-head-title"),
    RESULTS_HEAD_TOTAL("results-head-total"),
    RESULTS_HEAD_AVG("results-head-avg"),
    RESULTS_HEAD_PEAK("results-head-peak"),
    RESULTS_HEAD_SPAN("results-head-span"),
    RESULTS_PANE_TITLE("results-pane-title"),
    RESULTS_COL_PROB("results-col-prob"),
    RESULTS_COL_MODEL("results-col-model"),
    RESULTS_COL_SERVER("results-col-server"),
    RESULTS_COL_TIME("results-col-time"),
    RESULTS_TIME_NOW("results-time-now"),
    USAGE_RESULTS("usage-results"),
    HELP_RESULTS("help-results"),

    DATACOLLECT_START_SUCCESS("datacollect-start-success"),
    DATACOLLECT_START_RESTARTED("datacollect-start-restarted"),
    DATACOLLECT_STOP_SUCCESS("datacollect-stop-success"),
    DATACOLLECT_STOP_FAIL("datacollect-stop-fail"),
    DATACOLLECT_CANCEL_SUCCESS("datacollect-cancel-success"),
    DATACOLLECT_STATUS_HEADER("datacollect-status-header"),
    DATACOLLECT_STATUS_ENTRY("datacollect-status-entry"),
    DATACOLLECT_STATUS_EMPTY("datacollect-status-empty"),
    DATACOLLECT_STATUS_NO_SESSION("datacollect-status-no-session"),
    DATACOLLECT_INVALID_TYPE("datacollect-invalid-type"),
    DATACOLLECT_DETAILS_REQUIRED("datacollect-details-required"),

    CROSSSERVER_ALERT("crossserver-alert"),
    CROSSSERVER_ENABLED("crossserver-enabled"),
    CROSSSERVER_DISABLED("crossserver-disabled"),

    SUSPECTS_MENU_PREV("menu-prev"),
    SUSPECTS_MENU_NEXT("menu-next"),
    SUSPECTS_MENU_CLOSE("menu-close"),
    MENU_EMPTY_TITLE("menu-empty-title"),
    MENU_PAGE("menu-page"),
    MENU_PLAYER_OFFLINE("menu-player-offline"),
    MENU_UNSAFE_NAME("menu-unsafe-name"),

    LIVE_MENU_OPEN("live-menu-open"),
    LIVE_MENU_TITLE("live-menu-title"),
    LIVE_MENU_EMPTY("live-menu-empty"),
    LIVE_MENU_NAME("live-menu-name"),
    LIVE_MENU_CHECKS("live-menu-checks"),
    LIVE_MENU_ROW("live-menu-row"),
    LIVE_MENU_RISK("live-menu-risk"),
    LIVE_MENU_LEVEL("live-menu-level"),
    LIVE_MENU_LAST("live-menu-last"),
    LIVE_MENU_WATCH("live-menu-watch"),
    LIVE_MENU_INFO_TITLE("live-menu-info-title"),
    LIVE_MENU_INFO_COUNT("live-menu-info-count"),
    LIVE_MENU_INFO_WINDOW("live-menu-info-window"),
    REPUTATION_NOTICE("reputation-join-notice"),
    ALERT_CLICK_HINT("alert-click-hint"),
    UNIT_DAYS("unit-d"),
    UNIT_HOURS("unit-h"),
    UNIT_MINUTES("unit-m"),
    UNIT_SECONDS("unit-s"),
    COMMON_YES("common-yes"),
    COMMON_NO("common-no"),
    COMMON_ON("common-on"),
    COMMON_OFF("common-off"),
    STATS_DETECTIONS("stats-detections"),

    USAGE_PROFILE("usage-profile"),
    USAGE_PROB("usage-prob"),
    USAGE_EXEMPT("usage-exempt"),
    USAGE_EXEMPT_REMOVE("usage-exempt-remove"),
    USAGE_EXEMPT_STATUS("usage-exempt-status"),
    USAGE_PUNISH("usage-punish"),
    USAGE_STATS("usage-stats"),
    USAGE_DC_STOP("usage-dc-stop"),
    USAGE_DC_CANCEL("usage-dc-cancel"),

    HELP_HEADER("help-header"),
    HELP_RELOAD("help-reload"),
    HELP_ALERTS("help-alerts"),
    HELP_MONITOR("help-monitor"),
    HELP_PROFILE("help-profile"),
    HELP_MENU("help-menu"),
    HELP_DEBUG("help-debug"),
    HELP_PROB("help-prob"),
    HELP_EXEMPT("help-exempt"),
    HELP_PUNISH("help-punish"),
    HELP_STATS("help-stats"),
    HELP_LOG("help-log"),
    HELP_CROSSSERVER("help-crossserver"),
    HELP_DATACOLLECT("help-datacollect"),
    HELP_FOOTER("help-footer"),

    DC_HELP_HEADER("dc-help-header"),
    DC_HELP_START("dc-help-start"),
    DC_HELP_STOP("dc-help-stop"),
    DC_HELP_CANCEL("dc-help-cancel"),
    DC_HELP_STATUS("dc-help-status"),
    DC_HELP_FOOTER("dc-help-footer"),
}
